apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "flask-postgres.fullname" . }}-flask

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: flask

  template:
    metadata:
      labels:
        app: flask

    spec:
  
      serviceAccountName: {{ include "flask-postgres.fullname" . }}-flask
      
      containers:
        - name: flask
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}

          ports:
            - containerPort: 5006

          env:
            - name: DB_HOST
              value: '{{ include "flask-postgres.fullname" . }}-postgres-service'

            - name: DB_PORT
              value: "{{ .Values.database.port }}"

            - name: DB_NAME
              value: "{{ .Values.database.name }}"

            - name: DB_USER
              value: "{{ .Values.database.user }}"

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "flask-postgres.fullname" . }}-secret
                  key: POSTGRES_PASSWORD
