replicaCount: 1

image:
  repository: kubernetes-flask
  tag: v2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5006

postgres:
  image:
    repository: postgres
    tag: "16"

  database: employees
  username: Ayush

  storage:
    size: 1Gi

database:
  host: postgres-service
  port: 5432
  name: employees
  user: Ayush
